const localeMaps = {
  USD: {
    enUS: new Map<number, string>([
      [1, "One Dollar and Zero Cents"],
      [2.32, "Two Dollars and Thirty-Two Cents"],
      [7, "Seven Dollars and Zero Cents"],
      [11.99, "Eleven Dollars and Ninety-Nine Cents"],
      [106.47, "One Hundred Six Dollars and Forty-Seven Cents"],
      [786.56, "Seven Hundred Eighty-Six Dollars and Fifty-Six Cents"],
      [1042, "One Thousand Forty-Two Dollars and Zero Cents"],
      [1055.0, "One Thousand Fifty-Five Dollars and Zero Cents"],
      [7786.49, "Seven Thousand Seven Hundred Eighty-Six Dollars and Forty-Nine Cents"],
      [18166.56, "Eighteen Thousand One Hundred Sixty-Six Dollars and Fifty-Six Cents"],
      [667842.71, "Six Hundred Sixty-Seven Thousand Eight Hundred Forty-Two Dollars and Seventy-One Cents"],
      [1004256.99, "One Million Four Thousand Two Hundred Fifty-Six Dollars and Ninety-Nine Cents"],
      [9999999.99, "Nine Million Nine Hundred Ninety-Nine Thousand Nine Hundred Ninety-Nine Dollars and Ninety-Nine Cents"],
      [440096212.87, "Four Hundred Forty Million Ninety-Six Thousand Two Hundred Twelve Dollars and Eighty-Seven Cents"],
      [1000000000.0, "One Billion Dollars and Zero Cents"],
      [44123001000.48, "Forty-Four Billion One Hundred Twenty-Three Million One Thousand Dollars and Forty-Eight Cents"],
      [3677000000010, "Three Trillion Six Hundred Seventy-Seven Billion Ten Dollars and Zero Cents"],
    ]),
    plPL: new Map<number, string>([
      [1, "Jeden Dolar i Zero Centów"],
      [2.32, "Dwa Dolary i Trzydzieści Dwa Centy"],
      [7, "Siedem Dolarów i Zero Centów"],
      [11.99, "Jedenaście Dolarów i Dziewięćdziesiąt Dziewięć Centów"],
      [106.47, "Sto Sześć Dolarów i Czterdzieści Siedem Centów"],
      [786.56, "Siedemset Osiemdziesiąt Sześć Dolarów i Pięćdziesiąt Sześć Centów"],
      [1042, "Jeden Tysiąc Czterdzieści Dwa Dolary i Zero Centów"],
      [1055.0, "Jeden Tysiąc Pięćdziesiąt Pięć Dolarów i Zero Centów"],
      [7786.49, "Siedem Tysięcy Siedemset Osiemdziesiąt Sześć Dolarów i Czterdzieści Dziewięć Centów"],
      [18166.56, "Osiemnaście Tysięcy Sto Sześćdziesiąt Sześć Dolarów i Pięćdziesiąt Sześć Centów"],
      [667842.71, "Sześćset Sześćdziesiąt Siedem Tysięcy Osiemset Czterdzieści Dwa Dolary i Siedemdziesiąt Jeden Centów"],
      [1004256.99, "Jeden Milion Cztery Tysiące Dwieście Pięćdziesiąt Sześć Dolarów i Dziewięćdziesiąt Dziewięć Centów"],
      [9999999.99, "Dziewięć Milionów Dziewięćset Dziewięćdziesiąt Dziewięć Tysięcy Dziewięćset Dziewięćdziesiąt Dziewięć Dolarów i Dziewięćdziesiąt Dziewięć Centów"],
      [440096212.87, "Czterysta Czterdzieści Milionów Dziewięćdziesiąt Sześć Tysięcy Dwieście Dwanaście Dolarów i Osiemdziesiąt Siedem Centów"],
      [1000000000.0, "Jeden Miliard Dolarów i Zero Centów"],
      [44123001000.48, "Czterdzieści Cztery Miliardy Sto Dwadzieścia Trzy Miliony Jeden Tysiąc Dolarów i Czterdzieści Osiem Centów"],
      [3677000000010, "Trzy Biliony Sześćset Siedemdziesiąt Siedem Miliardów Dziesięć Dolarów i Zero Centów"],
    ]),
  },
};

export default localeMaps;
